import type { Lesson, LevelMeta } from "./types";

export const LEVELS: LevelMeta[] = [
  {
    level: "A1",
    title: "A1 — Beginner (≈ weeks 1–10)",
    description:
      "Greet people, introduce yourself, count, and form simple present-tense sentences. The foundation everything else builds on — take your time here.",
    examFocus:
      "Foundation for the TEF/TCF: basic comprehension and survival phrases.",
  },
  {
    level: "A2",
    title: "A2 — Elementary (≈ weeks 11–22)",
    description:
      "Talk about daily routines, describe the past (passé composé), and express simple opinions in writing and speech.",
    examFocus: "TEF/TCF: short dialogues, simple notes, and everyday messages.",
  },
  {
    level: "B1",
    title: "B1 — Intermediate (≈ weeks 23–38)",
    description:
      "Handle most everyday situations, narrate experiences, justify an opinion, and use all the common tenses including the conditionnel.",
    examFocus: "TEF/TCF: structured opinions, longer reading and listening passages.",
  },
  {
    level: "B2",
    title: "B2 — Upper-intermediate · your exam target (≈ weeks 39–52)",
    description:
      "Argue fluently with nuance, use the subjonctif and a formal register, and write structured argumentative essays.",
    examFocus:
      "TEF/TCF B2+: formal letters, argumentative essays, and nuanced debate.",
  },
];

// ---------------------------------------------------------------------------
// A1 lessons — real, usable content. Add more lessons/levels by appending.
// ---------------------------------------------------------------------------

export const LESSONS: Lesson[] = [
  {
    id: "a1-01",
    level: "A1",
    order: 1,
    title: "Bonjour ! — Greetings",
    goal: "Greet someone and say goodbye politely.",
    grammar: "Use « vous » for formal/strangers and « tu » for friends/family.",
    vocab: [
      { fr: "bonjour", en: "hello / good morning" },
      { fr: "bonsoir", en: "good evening" },
      { fr: "salut", en: "hi / bye (informal)" },
      { fr: "au revoir", en: "goodbye" },
      { fr: "merci", en: "thank you" },
      { fr: "s'il vous plaît", en: "please (formal)" },
      { fr: "oui", en: "yes" },
      { fr: "non", en: "no" },
      {
        fr: "Comment allez-vous ?",
        en: "How are you? (formal)",
        exampleFr: "Bonjour, comment allez-vous ?",
        exampleEn: "Hello, how are you?",
      },
      { fr: "Ça va ?", en: "How's it going? (informal)" },
    ],
    exercises: [
      {
        id: "a1-01-e1",
        type: "flashcard",
        prompt: "Learn this word. Tap to reveal the meaning.",
        vocab: { fr: "bonjour", en: "hello / good morning" },
      },
      {
        id: "a1-01-e2",
        type: "flashcard",
        prompt: "Learn this word. Tap to reveal the meaning.",
        vocab: { fr: "merci", en: "thank you" },
      },
      {
        id: "a1-01-e3",
        type: "multipleChoice",
        prompt: "Choose the correct meaning.",
        question: "What does « au revoir » mean?",
        options: ["hello", "goodbye", "thank you", "please"],
        answerIndex: 1,
        speak: "au revoir",
      },
      {
        id: "a1-01-e4",
        type: "multipleChoice",
        prompt: "Which greeting is informal?",
        question: "Pick the informal greeting.",
        options: ["bonjour", "salut", "bonsoir", "au revoir"],
        answerIndex: 1,
        explanation: "« Salut » is casual — use it with friends, not strangers.",
      },
      {
        id: "a1-01-e5",
        type: "listening",
        prompt: "Listen and type what you hear (in French).",
        audioText: "bonsoir",
        answers: ["bonsoir"],
        showText: true,
      },
      {
        id: "a1-01-e6",
        type: "matchPairs",
        prompt: "Match the French to its English meaning.",
        pairs: [
          { fr: "merci", en: "thank you" },
          { fr: "oui", en: "yes" },
          { fr: "non", en: "no" },
          { fr: "salut", en: "hi" },
        ],
      },
      {
        id: "a1-01-e7",
        type: "translate",
        prompt: "Translate to French.",
        source: "Hello, thank you.",
        direction: "enToFr",
        answers: ["bonjour, merci", "bonjour merci"],
        explanation: "« Bonjour, merci. » — punctuation and capitals don't matter here.",
      },
    ],
  },
  {
    id: "a1-02",
    level: "A1",
    order: 2,
    title: "Je m'appelle… — Introducing yourself",
    goal: "Say your name, where you're from, and ask someone theirs.",
    grammar:
      "« s'appeler » is reflexive: je m'appelle, tu t'appelles, il/elle s'appelle.",
    vocab: [
      { fr: "Je m'appelle…", en: "My name is…" },
      { fr: "Comment vous appelez-vous ?", en: "What's your name? (formal)" },
      { fr: "Tu t'appelles comment ?", en: "What's your name? (informal)" },
      { fr: "Enchanté(e)", en: "Nice to meet you" },
      { fr: "Je suis…", en: "I am…" },
      { fr: "Je viens de…", en: "I come from…" },
      { fr: "J'habite à…", en: "I live in…" },
      { fr: "Et vous ?", en: "And you? (formal)" },
    ],
    exercises: [
      {
        id: "a1-02-e1",
        type: "flashcard",
        prompt: "Learn this phrase.",
        vocab: {
          fr: "Je m'appelle…",
          en: "My name is…",
          exampleFr: "Je m'appelle Marie.",
          exampleEn: "My name is Marie.",
        },
      },
      {
        id: "a1-02-e2",
        type: "fillBlank",
        prompt: "Fill in the reflexive pronoun.",
        sentence: "Je ___ appelle Paul.",
        answers: ["m'", "m"],
        hintEn: "I call myself…",
        explanation: "« Je m'appelle » — the reflexive « me » becomes « m' » before a vowel.",
      },
      {
        id: "a1-02-e3",
        type: "multipleChoice",
        prompt: "Choose the correct response.",
        question: "Someone says « Enchanté ! ». It means:",
        options: ["I'm leaving", "Nice to meet you", "I'm hungry", "See you"],
        answerIndex: 1,
      },
      {
        id: "a1-02-e4",
        type: "translate",
        prompt: "Translate to French.",
        source: "I live in Paris.",
        direction: "enToFr",
        answers: ["j'habite à paris", "jhabite a paris"],
      },
      {
        id: "a1-02-e5",
        type: "listening",
        prompt: "Listen and type the phrase.",
        audioText: "Je viens de Paris.",
        answers: ["je viens de paris"],
        showText: true,
      },
      {
        id: "a1-02-e6",
        type: "writing",
        prompt: "Write a short self-introduction.",
        taskFr:
          "Présentez-vous en 2 ou 3 phrases : votre nom, d'où vous venez, où vous habitez.",
        minWords: 8,
        targetLevel: "A1",
      },
    ],
  },
  {
    id: "a1-03",
    level: "A1",
    order: 3,
    title: "Les nombres — Numbers 0–20",
    goal: "Count from 0 to 20 and give your phone number or age.",
    grammar: "« avoir » for age: J'ai 25 ans (literally 'I have 25 years').",
    vocab: [
      { fr: "zéro", en: "0" },
      { fr: "un", en: "1" },
      { fr: "deux", en: "2" },
      { fr: "trois", en: "3" },
      { fr: "quatre", en: "4" },
      { fr: "cinq", en: "5" },
      { fr: "six", en: "6" },
      { fr: "sept", en: "7" },
      { fr: "huit", en: "8" },
      { fr: "neuf", en: "9" },
      { fr: "dix", en: "10" },
      { fr: "onze", en: "11" },
      { fr: "douze", en: "12" },
      { fr: "treize", en: "13" },
      { fr: "quatorze", en: "14" },
      { fr: "quinze", en: "15" },
      { fr: "seize", en: "16" },
      { fr: "dix-sept", en: "17" },
      { fr: "dix-huit", en: "18" },
      { fr: "dix-neuf", en: "19" },
      { fr: "vingt", en: "20" },
    ],
    exercises: [
      {
        id: "a1-03-e1",
        type: "multipleChoice",
        prompt: "Choose the correct number.",
        question: "What is « quinze »?",
        options: ["5", "15", "50", "16"],
        answerIndex: 1,
      },
      {
        id: "a1-03-e2",
        type: "fillBlank",
        prompt: "Write the number in French.",
        sentence: "7 = ___",
        answers: ["sept"],
      },
      {
        id: "a1-03-e3",
        type: "listening",
        prompt: "Listen and type the number in French.",
        audioText: "treize",
        answers: ["treize"],
        showText: true,
      },
      {
        id: "a1-03-e4",
        type: "translate",
        prompt: "Translate to French.",
        source: "I am 20 years old.",
        direction: "enToFr",
        answers: ["j'ai vingt ans", "jai vingt ans"],
        explanation: "Age uses « avoir »: J'ai vingt ans.",
      },
      {
        id: "a1-03-e5",
        type: "matchPairs",
        prompt: "Match the number to its digit.",
        pairs: [
          { fr: "quatre", en: "4" },
          { fr: "neuf", en: "9" },
          { fr: "douze", en: "12" },
          { fr: "dix-huit", en: "18" },
        ],
      },
    ],
  },
  {
    id: "a1-04",
    level: "A1",
    order: 4,
    title: "Être & Avoir — The two key verbs",
    goal: "Conjugate « être » (to be) and « avoir » (to have) in the present.",
    grammar:
      "être: je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. avoir: j'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.",
    vocab: [
      { fr: "je suis", en: "I am" },
      { fr: "tu es", en: "you are (informal)" },
      { fr: "il/elle est", en: "he/she is" },
      { fr: "nous sommes", en: "we are" },
      { fr: "vous êtes", en: "you are (formal/plural)" },
      { fr: "ils/elles sont", en: "they are" },
      { fr: "j'ai", en: "I have" },
      { fr: "tu as", en: "you have" },
      { fr: "il/elle a", en: "he/she has" },
      { fr: "nous avons", en: "we have" },
      { fr: "vous avez", en: "you have" },
      { fr: "ils/elles ont", en: "they have" },
    ],
    exercises: [
      {
        id: "a1-04-e1",
        type: "fillBlank",
        prompt: "Conjugate « être ».",
        sentence: "Je ___ étudiant.",
        answers: ["suis"],
        hintEn: "I am a student.",
      },
      {
        id: "a1-04-e2",
        type: "fillBlank",
        prompt: "Conjugate « avoir ».",
        sentence: "Nous ___ deux enfants.",
        answers: ["avons"],
        hintEn: "We have two children.",
      },
      {
        id: "a1-04-e3",
        type: "multipleChoice",
        prompt: "Pick the correct form.",
        question: "Vous ___ français ?",
        options: ["es", "êtes", "sommes", "sont"],
        answerIndex: 1,
        explanation: "« vous êtes » — note the circumflex and liaison.",
      },
      {
        id: "a1-04-e4",
        type: "translate",
        prompt: "Translate to French.",
        source: "She is tired.",
        direction: "enToFr",
        answers: ["elle est fatiguée", "elle est fatigue"],
      },
      {
        id: "a1-04-e5",
        type: "listening",
        prompt: "Listen and type what you hear.",
        audioText: "Ils ont une voiture.",
        answers: ["ils ont une voiture"],
        showText: true,
      },
      {
        id: "a1-04-e6",
        type: "writing",
        prompt: "Describe yourself using être and avoir.",
        taskFr:
          "Écrivez 2 phrases : une avec « être » et une avec « avoir » (par exemple votre âge).",
        minWords: 8,
        targetLevel: "A1",
      },
    ],
  },

  // -------------------------------------------------------------------------
  // A2 lessons — daily life, the past, plans, and simple opinions.
  // -------------------------------------------------------------------------
  {
    id: "a2-01",
    level: "A2",
    order: 1,
    title: "Ma routine — Daily routine & reflexive verbs",
    goal: "Describe your daily routine using reflexive (pronominal) verbs.",
    grammar:
      "Reflexive verbs take an extra pronoun: je me lève, tu te lèves, il/elle se lève, nous nous levons, vous vous levez, ils/elles se lèvent.",
    vocab: [
      { fr: "se lever", en: "to get up", exampleFr: "Je me lève à 7 heures.", exampleEn: "I get up at 7." },
      { fr: "se laver", en: "to wash (oneself)" },
      { fr: "s'habiller", en: "to get dressed" },
      { fr: "se brosser les dents", en: "to brush one's teeth" },
      { fr: "se coucher", en: "to go to bed" },
      { fr: "se réveiller", en: "to wake up" },
      { fr: "d'abord", en: "first" },
      { fr: "ensuite", en: "then / next" },
      { fr: "enfin", en: "finally" },
      { fr: "tous les jours", en: "every day" },
    ],
    exercises: [
      {
        id: "a2-01-e1",
        type: "flashcard",
        prompt: "Learn this reflexive verb.",
        vocab: { fr: "se lever", en: "to get up", exampleFr: "Je me lève tôt.", exampleEn: "I get up early." },
      },
      {
        id: "a2-01-e2",
        type: "fillBlank",
        prompt: "Add the reflexive pronoun.",
        sentence: "Je ___ lave le matin.",
        answers: ["me"],
        hintEn: "I wash myself in the morning.",
        explanation: "First person reflexive pronoun is « me »: je me lave.",
      },
      {
        id: "a2-01-e3",
        type: "fillBlank",
        prompt: "Conjugate « se coucher ».",
        sentence: "Nous nous ___ à 23 heures.",
        answers: ["couchons"],
        hintEn: "We go to bed at 11pm.",
        explanation: "nous nous couchons — note the double « nous ».",
      },
      {
        id: "a2-01-e4",
        type: "multipleChoice",
        prompt: "Which word means 'then / next'?",
        question: "Choose the correct connector.",
        options: ["d'abord", "ensuite", "enfin", "tous les jours"],
        answerIndex: 1,
      },
      {
        id: "a2-01-e5",
        type: "listening",
        prompt: "Listen and type the sentence.",
        audioText: "Je me réveille à six heures.",
        answers: ["je me réveille à six heures", "je me reveille a six heures"],
        showText: true,
      },
      {
        id: "a2-01-e6",
        type: "translate",
        prompt: "Translate to French.",
        source: "She gets dressed.",
        direction: "enToFr",
        answers: ["elle s'habille", "elle shabille"],
      },
      {
        id: "a2-01-e7",
        type: "writing",
        prompt: "Describe your morning routine.",
        taskFr:
          "Décrivez votre routine du matin en 3 ou 4 phrases. Utilisez « d'abord », « ensuite » et « enfin ».",
        minWords: 20,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-02",
    level: "A2",
    order: 2,
    title: "Le passé composé (avec « avoir »)",
    goal: "Talk about completed past actions using avoir + past participle.",
    grammar:
      "passé composé = présent de « avoir » + participe passé. -er → -é (parler→parlé), -ir → -i (finir→fini). Irregulars: avoir→eu, être→été, faire→fait, voir→vu.",
    vocab: [
      { fr: "hier", en: "yesterday" },
      { fr: "hier soir", en: "last night" },
      { fr: "la semaine dernière", en: "last week" },
      { fr: "j'ai mangé", en: "I ate / I have eaten" },
      { fr: "j'ai travaillé", en: "I worked" },
      { fr: "j'ai fait", en: "I did / I made" },
      { fr: "j'ai vu", en: "I saw" },
      { fr: "j'ai pris", en: "I took / I had (food)" },
      { fr: "déjà", en: "already" },
      { fr: "ne… pas encore", en: "not yet" },
    ],
    exercises: [
      {
        id: "a2-02-e1",
        type: "flashcard",
        prompt: "Learn this past-tense phrase.",
        vocab: { fr: "j'ai mangé", en: "I ate", exampleFr: "Hier, j'ai mangé une pizza.", exampleEn: "Yesterday I ate a pizza." },
      },
      {
        id: "a2-02-e2",
        type: "fillBlank",
        prompt: "Give the past participle of « parler ».",
        sentence: "J'ai ___ avec Marie hier.",
        answers: ["parlé", "parle"],
        hintEn: "I spoke with Marie yesterday.",
        explanation: "-er verbs form the participle with -é: parler → parlé.",
      },
      {
        id: "a2-02-e3",
        type: "multipleChoice",
        prompt: "Choose the correct past participle.",
        question: "Tu as ___ tes devoirs ? (finir)",
        options: ["fini", "finu", "finé", "finir"],
        answerIndex: 0,
        explanation: "-ir verbs like finir form the participle with -i: fini.",
      },
      {
        id: "a2-02-e4",
        type: "fillBlank",
        prompt: "Use the auxiliary « avoir ».",
        sentence: "Nous ___ vu un bon film.",
        answers: ["avons"],
        hintEn: "We saw a good film.",
        explanation: "passé composé = avoir (avons) + participle (vu).",
      },
      {
        id: "a2-02-e5",
        type: "translate",
        prompt: "Translate to French.",
        source: "I worked yesterday.",
        direction: "enToFr",
        answers: ["j'ai travaillé hier", "jai travaille hier"],
      },
      {
        id: "a2-02-e6",
        type: "listening",
        prompt: "Listen and type what you hear.",
        audioText: "Hier, j'ai fait du sport.",
        answers: ["hier j'ai fait du sport", "hier jai fait du sport"],
        showText: true,
      },
      {
        id: "a2-02-e7",
        type: "writing",
        prompt: "Say what you did yesterday.",
        taskFr:
          "Qu'est-ce que vous avez fait hier ? Écrivez 3 phrases au passé composé.",
        minWords: 18,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-03",
    level: "A2",
    order: 3,
    title: "Le passé composé (avec « être »)",
    goal: "Use être for movement/state verbs and make the participle agree.",
    grammar:
      "Some verbs use « être »: aller, venir, partir, arriver, entrer, sortir, monter, descendre, rester, tomber, naître, mourir, and all reflexives. The participle agrees: elle est allée, ils sont partis.",
    vocab: [
      { fr: "je suis allé(e)", en: "I went" },
      { fr: "je suis venu(e)", en: "I came" },
      { fr: "je suis parti(e)", en: "I left" },
      { fr: "je suis arrivé(e)", en: "I arrived" },
      { fr: "je suis resté(e)", en: "I stayed" },
      { fr: "je suis sorti(e)", en: "I went out" },
      { fr: "elle est née", en: "she was born" },
      { fr: "il est tombé", en: "he fell" },
    ],
    exercises: [
      {
        id: "a2-03-e1",
        type: "flashcard",
        prompt: "Learn this past-tense phrase.",
        vocab: { fr: "je suis allé(e)", en: "I went", exampleFr: "Je suis allée à Paris.", exampleEn: "I went to Paris." },
      },
      {
        id: "a2-03-e2",
        type: "multipleChoice",
        prompt: "Which auxiliary does « aller » take?",
        question: "Je ___ allé au cinéma.",
        options: ["ai", "suis", "as", "est"],
        answerIndex: 1,
        explanation: "Verbs of movement like aller use « être »: je suis allé.",
      },
      {
        id: "a2-03-e3",
        type: "fillBlank",
        prompt: "Make the participle agree (feminine).",
        sentence: "Marie est ___ à 8 heures. (partir)",
        answers: ["partie"],
        hintEn: "Marie left at 8.",
        explanation: "With être, the participle agrees: Marie est partie (feminine -e).",
      },
      {
        id: "a2-03-e4",
        type: "fillBlank",
        prompt: "Make the participle agree (plural masculine).",
        sentence: "Ils sont ___ ensemble. (arriver)",
        answers: ["arrivés", "arrives"],
        hintEn: "They arrived together.",
        explanation: "Plural masculine adds -s: ils sont arrivés.",
      },
      {
        id: "a2-03-e5",
        type: "translate",
        prompt: "Translate to French (you are male).",
        source: "I stayed at home.",
        direction: "enToFr",
        answers: ["je suis resté à la maison", "je suis reste a la maison", "je suis resté chez moi"],
      },
      {
        id: "a2-03-e6",
        type: "listening",
        prompt: "Listen and type the sentence.",
        audioText: "Elle est venue hier soir.",
        answers: ["elle est venue hier soir"],
        showText: true,
      },
      {
        id: "a2-03-e7",
        type: "writing",
        prompt: "Describe a recent outing.",
        taskFr:
          "Racontez une sortie récente : où êtes-vous allé(e) ? Avec qui ? Utilisez « être » au passé composé (3 phrases).",
        minWords: 20,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-04",
    level: "A2",
    order: 4,
    title: "L'imparfait — Describing the past",
    goal: "Describe past habits, settings, and ongoing states with the imperfect.",
    grammar:
      "imparfait stem = « nous » form minus -ons, plus endings -ais, -ais, -ait, -ions, -iez, -aient. parler→je parlais. Exception: être→j'étais. Use it for habits and descriptions; passé composé for single completed actions.",
    vocab: [
      { fr: "quand j'étais petit(e)", en: "when I was little" },
      { fr: "avant", en: "before / in the past" },
      { fr: "souvent", en: "often" },
      { fr: "toujours", en: "always" },
      { fr: "il y avait", en: "there was / there were" },
      { fr: "il faisait beau", en: "the weather was nice" },
      { fr: "je jouais", en: "I used to play / I was playing" },
      { fr: "c'était", en: "it was" },
    ],
    exercises: [
      {
        id: "a2-04-e1",
        type: "flashcard",
        prompt: "Learn this imperfect phrase.",
        vocab: { fr: "quand j'étais petit(e)", en: "when I was little", exampleFr: "Quand j'étais petit, je jouais au foot.", exampleEn: "When I was little, I played football." },
      },
      {
        id: "a2-04-e2",
        type: "fillBlank",
        prompt: "Conjugate « être » in the imperfect.",
        sentence: "Quand j'___ jeune, j'habitais à Lyon.",
        answers: ["étais", "etais"],
        hintEn: "When I was young…",
        explanation: "être is irregular in the imparfait: j'étais.",
      },
      {
        id: "a2-04-e3",
        type: "multipleChoice",
        prompt: "Which tense for a repeated past habit?",
        question: "« Every summer we went to the sea » uses…",
        options: ["passé composé", "imparfait", "futur proche", "présent"],
        answerIndex: 1,
        explanation: "Repeated habits in the past use the imparfait.",
      },
      {
        id: "a2-04-e4",
        type: "fillBlank",
        prompt: "Conjugate « jouer » in the imperfect.",
        sentence: "Nous ___ dans le jardin. (jouer)",
        answers: ["jouions"],
        hintEn: "We used to play in the garden.",
        explanation: "nous jouions — imperfect ending -ions on the jou- stem.",
      },
      {
        id: "a2-04-e5",
        type: "translate",
        prompt: "Translate to French.",
        source: "The weather was nice.",
        direction: "enToFr",
        answers: ["il faisait beau"],
      },
      {
        id: "a2-04-e6",
        type: "listening",
        prompt: "Listen and type the sentence.",
        audioText: "Avant, il y avait un cinéma ici.",
        answers: ["avant il y avait un cinéma ici", "avant il y avait un cinema ici"],
        showText: true,
      },
      {
        id: "a2-04-e7",
        type: "writing",
        prompt: "Describe your childhood.",
        taskFr:
          "Comment était votre vie quand vous étiez petit(e) ? Écrivez 3 phrases à l'imparfait.",
        minWords: 20,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-05",
    level: "A2",
    order: 5,
    title: "Le futur proche — Talking about plans",
    goal: "Say what you are going to do using aller + infinitive.",
    grammar:
      "futur proche = présent de « aller » + infinitif. Je vais manger, tu vas partir, il va venir, nous allons voir, vous allez faire, ils vont arriver.",
    vocab: [
      { fr: "demain", en: "tomorrow" },
      { fr: "ce week-end", en: "this weekend" },
      { fr: "la semaine prochaine", en: "next week" },
      { fr: "bientôt", en: "soon" },
      { fr: "je vais faire", en: "I'm going to do/make" },
      { fr: "je vais voir", en: "I'm going to see" },
      { fr: "avoir l'intention de", en: "to intend to" },
      { fr: "un projet", en: "a plan / project", gender: "m" },
    ],
    exercises: [
      {
        id: "a2-05-e1",
        type: "flashcard",
        prompt: "Learn this future phrase.",
        vocab: { fr: "je vais faire", en: "I'm going to do", exampleFr: "Demain, je vais faire les courses.", exampleEn: "Tomorrow I'm going to do the shopping." },
      },
      {
        id: "a2-05-e2",
        type: "fillBlank",
        prompt: "Conjugate « aller ».",
        sentence: "Nous ___ voir un film ce soir.",
        answers: ["allons"],
        hintEn: "We're going to watch a film tonight.",
        explanation: "futur proche: nous allons + infinitive.",
      },
      {
        id: "a2-05-e3",
        type: "multipleChoice",
        prompt: "Pick the correct form.",
        question: "Ils ___ partir demain.",
        options: ["va", "vont", "allons", "allez"],
        answerIndex: 1,
        explanation: "ils/elles vont + infinitive.",
      },
      {
        id: "a2-05-e4",
        type: "translate",
        prompt: "Translate to French.",
        source: "I'm going to travel next week.",
        direction: "enToFr",
        answers: [
          "je vais voyager la semaine prochaine",
        ],
      },
      {
        id: "a2-05-e5",
        type: "listening",
        prompt: "Listen and type what you hear.",
        audioText: "Ce week-end, je vais visiter Paris.",
        answers: ["ce week-end je vais visiter paris", "ce weekend je vais visiter paris"],
        showText: true,
      },
      {
        id: "a2-05-e6",
        type: "matchPairs",
        prompt: "Match the time expression to its meaning.",
        pairs: [
          { fr: "demain", en: "tomorrow" },
          { fr: "bientôt", en: "soon" },
          { fr: "ce week-end", en: "this weekend" },
          { fr: "la semaine prochaine", en: "next week" },
        ],
      },
      {
        id: "a2-05-e7",
        type: "writing",
        prompt: "Describe your weekend plans.",
        taskFr:
          "Qu'est-ce que vous allez faire ce week-end ? Écrivez 3 phrases au futur proche.",
        minWords: 18,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-06",
    level: "A2",
    order: 6,
    title: "Faire les courses — Shopping & quantities",
    goal: "Buy food and talk about quantities with partitive articles.",
    grammar:
      "Partitive articles (some/any): du (m), de la (f), de l' (vowel), des (plural). After a negative or a quantity, use « de »: pas de pain, beaucoup de lait, un kilo de pommes.",
    vocab: [
      { fr: "du pain", en: "(some) bread" },
      { fr: "de la viande", en: "(some) meat" },
      { fr: "de l'eau", en: "(some) water" },
      { fr: "des légumes", en: "(some) vegetables" },
      { fr: "un kilo de", en: "a kilo of" },
      { fr: "une bouteille de", en: "a bottle of" },
      { fr: "beaucoup de", en: "a lot of" },
      { fr: "Combien ça coûte ?", en: "How much does it cost?" },
      { fr: "le marché", en: "the market", gender: "m" },
      { fr: "l'addition", en: "the bill", gender: "f" },
    ],
    exercises: [
      {
        id: "a2-06-e1",
        type: "flashcard",
        prompt: "Learn this phrase.",
        vocab: { fr: "Combien ça coûte ?", en: "How much does it cost?", exampleFr: "Le pain, combien ça coûte ?", exampleEn: "The bread, how much is it?" },
      },
      {
        id: "a2-06-e2",
        type: "fillBlank",
        prompt: "Choose the right partitive article.",
        sentence: "Je voudrais ___ pain, s'il vous plaît. (some)",
        answers: ["du"],
        hintEn: "pain is masculine.",
        explanation: "« pain » is masculine → du pain.",
      },
      {
        id: "a2-06-e3",
        type: "fillBlank",
        prompt: "After a quantity, which word?",
        sentence: "Un kilo ___ pommes, s'il vous plaît.",
        answers: ["de", "d'"],
        hintEn: "a kilo OF apples",
        explanation: "After a quantity expression, use « de »: un kilo de pommes.",
      },
      {
        id: "a2-06-e4",
        type: "multipleChoice",
        prompt: "Choose the negative form.",
        question: "Je n'ai pas ___ lait.",
        options: ["du", "de la", "de", "des"],
        answerIndex: 2,
        explanation: "After a negative, partitives become « de »: pas de lait.",
      },
      {
        id: "a2-06-e5",
        type: "translate",
        prompt: "Translate to French.",
        source: "I would like some water.",
        direction: "enToFr",
        answers: ["je voudrais de l'eau", "je voudrais de leau"],
      },
      {
        id: "a2-06-e6",
        type: "listening",
        prompt: "Listen and type the question.",
        audioText: "Vous avez des légumes frais ?",
        answers: ["vous avez des légumes frais", "vous avez des legumes frais"],
        showText: true,
      },
      {
        id: "a2-06-e7",
        type: "writing",
        prompt: "Write a short market dialogue.",
        taskFr:
          "Écrivez un petit dialogue au marché : demandez deux produits et le prix (3-4 phrases).",
        minWords: 20,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-07",
    level: "A2",
    order: 7,
    title: "En ville — Directions & the city",
    goal: "Ask for and give directions around town.",
    grammar:
      "Imperative for directions: tournez, continuez, prenez, allez. Prepositions: à gauche, à droite, tout droit, à côté de, en face de, près de, loin de.",
    vocab: [
      { fr: "tout droit", en: "straight ahead" },
      { fr: "à gauche", en: "(to the) left" },
      { fr: "à droite", en: "(to the) right" },
      { fr: "à côté de", en: "next to" },
      { fr: "en face de", en: "across from" },
      { fr: "près de", en: "near" },
      { fr: "Où est… ?", en: "Where is…?" },
      { fr: "Tournez à droite", en: "Turn right" },
      { fr: "la gare", en: "the train station", gender: "f" },
      { fr: "la rue", en: "the street", gender: "f" },
    ],
    exercises: [
      {
        id: "a2-07-e1",
        type: "flashcard",
        prompt: "Learn this phrase.",
        vocab: { fr: "Où est la gare ?", en: "Where is the station?", exampleFr: "Excusez-moi, où est la gare ?", exampleEn: "Excuse me, where is the station?" },
      },
      {
        id: "a2-07-e2",
        type: "multipleChoice",
        prompt: "What does « tout droit » mean?",
        question: "Allez tout droit.",
        options: ["turn left", "straight ahead", "turn right", "go back"],
        answerIndex: 1,
        explanation: "« tout droit » = straight ahead (not 'right' — that's « à droite »).",
      },
      {
        id: "a2-07-e3",
        type: "fillBlank",
        prompt: "Complete the preposition.",
        sentence: "La banque est en ___ de la poste. (across from)",
        answers: ["face"],
        hintEn: "across from the post office",
        explanation: "en face de = across from / opposite.",
      },
      {
        id: "a2-07-e4",
        type: "matchPairs",
        prompt: "Match direction words to their meaning.",
        pairs: [
          { fr: "à gauche", en: "left" },
          { fr: "à droite", en: "right" },
          { fr: "près de", en: "near" },
          { fr: "à côté de", en: "next to" },
        ],
      },
      {
        id: "a2-07-e5",
        type: "translate",
        prompt: "Translate to French.",
        source: "Turn right, then go straight ahead.",
        direction: "enToFr",
        answers: [
          "tournez à droite, puis allez tout droit",
          "tournez a droite puis allez tout droit",
          "tournez à droite ensuite allez tout droit",
        ],
      },
      {
        id: "a2-07-e6",
        type: "listening",
        prompt: "Listen and type the directions.",
        audioText: "Prenez la première rue à gauche.",
        answers: ["prenez la première rue à gauche", "prenez la premiere rue a gauche"],
        showText: true,
      },
      {
        id: "a2-07-e7",
        type: "writing",
        prompt: "Give directions.",
        taskFr:
          "Quelqu'un cherche la gare. Donnez les directions depuis chez vous (3 phrases).",
        minWords: 18,
        targetLevel: "A2",
      },
    ],
  },
  {
    id: "a2-08",
    level: "A2",
    order: 8,
    title: "Donner son opinion — Opinions & connectors",
    goal: "Express and justify a simple opinion with linking words.",
    grammar:
      "Opinion starters: je pense que, je crois que, à mon avis, pour moi. Connectors: parce que (because), donc (so), mais (but), aussi (also). These are essential building blocks for B1/B2 writing.",
    vocab: [
      { fr: "je pense que", en: "I think that" },
      { fr: "je crois que", en: "I believe that" },
      { fr: "à mon avis", en: "in my opinion" },
      { fr: "je suis d'accord", en: "I agree" },
      { fr: "je ne suis pas d'accord", en: "I disagree" },
      { fr: "parce que", en: "because" },
      { fr: "donc", en: "so / therefore" },
      { fr: "par contre", en: "on the other hand" },
      { fr: "c'est pourquoi", en: "that's why" },
    ],
    exercises: [
      {
        id: "a2-08-e1",
        type: "flashcard",
        prompt: "Learn this opinion phrase.",
        vocab: { fr: "à mon avis", en: "in my opinion", exampleFr: "À mon avis, c'est une bonne idée.", exampleEn: "In my opinion, it's a good idea." },
      },
      {
        id: "a2-08-e2",
        type: "multipleChoice",
        prompt: "Which connector means 'because'?",
        question: "Choose the right word.",
        options: ["donc", "mais", "parce que", "aussi"],
        answerIndex: 2,
      },
      {
        id: "a2-08-e3",
        type: "fillBlank",
        prompt: "Add a connector meaning 'so/therefore'.",
        sentence: "Il pleut, ___ je reste à la maison.",
        answers: ["donc"],
        hintEn: "It's raining, so I'm staying home.",
        explanation: "« donc » links a cause to its consequence: …, donc je reste.",
      },
      {
        id: "a2-08-e4",
        type: "translate",
        prompt: "Translate to French.",
        source: "I think that French is useful.",
        direction: "enToFr",
        answers: [
          "je pense que le français est utile",
          "je pense que le francais est utile",
        ],
      },
      {
        id: "a2-08-e5",
        type: "listening",
        prompt: "Listen and type the opinion.",
        audioText: "Je ne suis pas d'accord avec toi.",
        answers: ["je ne suis pas d'accord avec toi", "je ne suis pas daccord avec toi"],
        showText: true,
      },
      {
        id: "a2-08-e6",
        type: "writing",
        prompt: "Give and justify an opinion.",
        taskFr:
          "Donnez votre opinion sur les réseaux sociaux. Utilisez « à mon avis » et « parce que » (3-4 phrases).",
        minWords: 25,
        targetLevel: "A2",
      },
    ],
  },
];

// --- Helpers -------------------------------------------------------------

export function getLessonsByLevel(level: string): Lesson[] {
  return LESSONS.filter((l) => l.level === level).sort((a, b) => a.order - b.order);
}

export function getLesson(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getNextLesson(id: string): Lesson | undefined {
  const idx = LESSONS.findIndex((l) => l.id === id);
  if (idx === -1 || idx + 1 >= LESSONS.length) return undefined;
  return LESSONS[idx + 1];
}
